sudo: false
addons:
  apt:
    packages:
    - oracle-java8-installer
language: java
jdk: oraclejdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2"
install: true
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/855ef506a5ef23e49ab7
    on_success: change
    on_failure: always
    on_start: never
after_success:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/pubring.gpg.enc
  -out $GPG_DIR/pubring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/secring.gpg.enc
  -out $GPG_DIR/secring.gpg -d
- "$GPG_DIR/publish.sh"
env:
  global:
  - GPG_DIR="`pwd`/deploy"
  - secure: ozPZXK+QTNfGi/Gay7Ih5yRz+X4efucoPMnqhn8+u0H/r/+HRCxSlJpH9sA1/ua3HUk7x/Tq7LIl+DdFe/wjkK8TB3G+/eundWZXIehzd9MUWRrWH9WDdEWF/vxBzqxzT1Uoz/959+Mr/IhjHFo40LxFDDOW0GStVuc4+IC0FoiY/p+0p7ripgiirOPb4xUQwuWFcOo8jZsvnRo7P27vvdbSMegftaEo7J/5DtaBxLVyTfzai9Cr+pWzl5Kdf87I25ohNJZ7dqSnNvlT/D60JgwMiWfGGjlW2noaVsmAmD8cQ5yUAt66KyX7mMlyLrvAC2OWhQ0WwlFwd5BWv6srHEhUu1zSuJpY15wqrqufTm5MYzRdjQh/1WsWovwVjUh3yT8gYj63fEGxCcV+hxHNwMwQVlsbbnLWw12+OWr2+hc+83zraGkIAIp4UnaOJb0FT3Jw+NHW378B4aWCHIHcRKUjwoZViMZxzlAO2kTt3BA1P8V3hduqT+wQ/7ooL504dksYt5XbK2GVS/sVfVQJOJD7/DjxhXBkjMUUAXTxjXTcJwFqGhnFPODqCG+S+Hk8YTR8qh9ZuB8bWSr1PXhTchNEGmaZTCzZDyE0M2Pnu+AAv3SP7CLaihsVKeaqynftriG2kqbUOkRh99PkxILVRQP6u1LZk5RublMK78gYpbM=
  - secure: y9mNrfn53N2bDR+R0Pdfl1aECtieKtXVHw64E9KlszMmGrMVeOhtg2JmrB6NSrMwFGQBldtZhk+fk0Xjek0qevL8UfvDo6AaUTZ1tuXSZeQnmAS8+KTZYJwxxzZQPEmKFG3trV4W39lMkS2zfS7Xs07hppbXO5NN2nVnbMMHjtRNvhYc7WymiKbD31+3M1L3VngZW1tHdJdRK7KezpwkyIqSumMx4JO1TeVFwP76d8VNuJN1EeiRwYcyBvmY/wcLxl+TeCizx4HzYcs/3uB71K52Yr8D5Gmy8wBWAPSRlJvgnrVf8RSQGN+2Nk0aUul7NmQ9xsRfT/gb4vMM0un8WpCIwiCwAf9M/3r/0oxCngyuDJ85T/C4KspJAQoYDxcRwcCCLED/lqkuifa2fcASPR9SPq9bloW+kidqdfgGL8XaSFTE0qL4K7b4TJV/lQPfQT2YV5slJaPdvY6yyshZBetOz7sj1/XhKtjZNSog532xKXEo2D1Jwx5qDQTx52F/kh2VEImVMUGhDOpVrZ2A+KtPfcYkoXT61ZXaEouATi1Ffuc2/n3hNItfuvGQ6N33GF4CFsWn5M3K0LvV/OI0JtM0rHJLGgwjYUaU85pOGE379lH3udPZzmzmgebulwr1disFs8T4ZJFUKhEwtjWGX4SCcVMfnJX9Vy5fJxvAd04=
  - secure: wXQH3ZR2PS4NhjhXReQE9/oI40ShhWejQ96re/3LY/JhnAkgubPKjjcpAPzcQV9ESE+AVQDdhtcEiOlN7CvnobsSzCmJ7L26qSX+9h27+ng8J7S2LWyqJ6Wflqzo+MWm3h6pynCrL9PIOEl1R1ZEr6kLNu3oV+GU/XrHKwY6CIaFkNxk61Wjf7uhpgKsPEcMGh28ru4bWpchx6LRpwasJ6K/XSRAMZ0694C5nGQXCRR3D4Y1HoUC8pRM9UOMc0Tli86e4aUgqLoQz9RzBt5sP5qP1LVdALgbgpzW812un6SWFT6V/wfyAJGfU0Nf8SLtp3oeFr1/5ERcxoage/U6elsjT5/VrFSCJzo2tv0Bifbq48Dg3bwgmek6+573fZ+xuJ8Z8NWeSqSRwSaktwQpmg6nJAS+bX7bJhcTm2Pwqs/rR3zrNnUtsygkB7JlSprpIrj6KC1qNEEZVDt7GhGGPkxux4O/Fqdc8CLm/W4denD9nzQKzO7ehwQ7F7j+tZsu8rNim9R/OqDGJq3FDjVkf/jC4X0TY9c5QUbnDMlz+jemAOWTS6Or7KT6vtPbAx1A25aOVsbIALG+MZMFPgPJsF5Mk8fvuPGQqJmZTA43wOM42tec8c/WbJZIyr5vcNnmgHK4atV6ajo6mlMekuQCSfFve0V8v9LK3vZRt6ELtiw=
  - secure: NRT/CJTI36ryEYA0WHehCoXIiEVlZhRQanF3iTdbKA9yuKx5o/DSHZKSKGEYIoPI+TDXEQfwNMmA7ZbxflLWjSFAOkJNSmCKuGmAoHfAkFLVDVlxaEtZ7O0fSkqRWLkd3sUFro9iC5NhLFTS9rM4oHmQoJHP50WRXpnuVVRUnFLyjaUdu9QG3boZ5KOAb1rToB0xO1nWKFD9a34ENwJZ3w/HA3shkaAnVkL+RlhgnKoZ2yMHatz2cfSuePwXoRmV++shOmLGMGDujrh6Fownk3IAYVpDujZFCEJdnXtzF/uOTf6Al89GXTCXcIJFnk8y+2x6IOUvpD1D9TCaeH7GbgGDbp1QHlTJRGMlF8dyssBMuvgdQVpHG/lG5DsnqIem1oG77B7e8osztSWdw7Zv3kWBOuRlKVqTZd3T7OzJJKU/vTQSTwtyOeZH/iK+u8PAfmRlPDzkO0cmfQ+MYjfgQv2qMFfK9xkxTP+E18sxXnfXanq6MD7sXG3+caf4Uv/5rN15t7v6v+Tjfdui2TcI50qT0qhB2YQLUJIZVPAc8DZt+RG16wrRKl+Adg9+D2E0oMUN678jeYsLJN5wI2ptn5HHy1jg9XzuEZ8yLb86hnxbXsHB5wU1tQbUZIWE6bVXvj3/oRSLhj2XLo5IBSjQNKE5F1ZTypPXawBAyPh4t6A=
  - secure: OGVZU4gx7z1hOz3No+xfvA47P0HNDoMluF1thqXp0fWEtAt2bjFs7E9iORGyE8gU9pKSdbkPJOGvELtR/P8W9wVFq2sm+izee0xwJTfEsw/p3oftwQtST6vYIpYgSjvoxKy9ZEi7XooZJG7gaZkRf+zSdSTPiVnit5m0d7OJkWBwSRbpTxds7qM8FbXR6mnHnbQ152c12Rsa7/8q1t/da6Gf3V+USLNgEmcbjYhgez/lt0DadorEsFWRym3H4rsxR8RRrdpTvNCCqUmpa3SuorDIEZ+nIP3apjCuG9H5sL89BCH+AX1v49I5wGeRDebX82xxtxiHxMfvRpmHzDm+mb8FpXBha8MjP2IwMe/F9MCGieMquuPflDOPA5YpuHsghOCwIrYlMbnHaYR1SjyJQVT41Ka/oVwVAKoefRHRp4MxLwcBbEO/5h3cPWe35+/rsWcVbtcsJfQ766/l9ZKdQ+3W6vZ8RMAteo++ydTu8X0+HKOaPpmkursY0j9aawijb1FAKAcb44l+6huzqDShcrTTzUtiuu+54KgPRBWp5IZOIBMD0bnnuNr3deYcwaE/jGaD+096rA1Q9BZCI6+kFxFfEMjPctKnd5PY3FFtxa5gtIK7ijyoSyH7rcOgKkhTcpnGY+rQRfBPs+/1ii3fSbD8YTaJuxItob8/L4EGGrc=
